### ISSUE TITLE
Smooth scroll / locations tabs in Chrome

### ISSUE THREAD

**Issue by gbrauer** [clrux/kaptiv8-dj#2]
From client - I've verified this as well:
"If I click through from the top nav bar, everything is fine. If i click through from the 4 locations block, it slowly scrolls down to the location i clicked on. then when i click on a different location tab, it immediately scrolls to the very bottom of the page."

**Comment by clrux** [comment]
This should be fixed in pull request https://github.com/clrux/kaptiv8-dj/pull/3
