### ISSUE TITLE
Smooth scroll / locations tabs in Chrome

### ISSUE THREAD

**Issue by gbrauer** [clrux/kaptiv8-dj#4]
It seems like it was working from the main homepage when I first checked, but now its not working from that page or this page for me: http://devorejohnson.staging.wpengine.com/for-contractors/ If I click on 'Kennesaw' from the Four locations section, it takes me to the Locations page, without the smooth scroll down to the tabs, and without Kennesaw set as the active tab. Athens is active.

**Comment by clrux** [comment]
Okay, try this one:

Pull request here: https://github.com/clrux/kaptiv8-dj/pull/3
Latest commit here: https://github.com/clrux/kaptiv8-dj/commit/4970b6cc165d376a1dcc0e1c644c2727ee256849
